import pandas as pd
import numpy as np
import os
import sys
from pydeseq2.dds import DeseqDataSet
from pydeseq2.preprocessing import deseq2_norm

def normalize_deseq2_no_report(raw_counts, fast=True, n_cpus=None):
    """
    Python equivalent of the normalizeDESeq2NoReport function.
    Accepts a DataFrame where genes are rows and samples are columns.
    """
    if n_cpus is None:
        n_cpus = os.cpu_count() or 1

    print(f"Starting DESeq2 normalization (threads: {n_cpus})...")

    # DESeq2 in Python expects matrix: samples as rows, genes as columns
    counts_t = raw_counts.T

    # Creating metadata (analogous to condition <- factor(rep("A", ...)))
    metadata = pd.DataFrame(
        {'condition': ['A'] * counts_t.shape[0]},
        index=counts_t.index
    )

    print("Creating DeseqDataSet object...")
    dds = DeseqDataSet(
        counts=counts_t,
        metadata=metadata,
        design_factors="condition",
        n_cpus=n_cpus
    )

    if fast:
        print("Estimating size factors and transformation (fast mode)...")
        dds.fit_size_factors()
        dds.vst(use_design=False, fit_type="mean")
    else:
        print("Estimating model parameters (full workflow)...")
        dds.deseq2()
        dds.vst(use_design=False)

    # Returning the result back in (genes x samples) orientation
    vst_counts = dds.layers["vst_counts"].T
    return pd.DataFrame(vst_counts, index=counts_t.columns, columns=counts_t.index)

def load_data(file_path):
    print(f"Loading data from {file_path}...")
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"File not found: {file_path}")

    # Attempt to load as CSV (with commas) or TSV (with tabs)
    if file_path.endswith('.csv'):
        return pd.read_csv(file_path, index_col=0)
    elif file_path.endswith('.tsv') or file_path.endswith('.txt'):
        return pd.read_csv(file_path, sep='\t', index_col=0)
    else:
        raise ValueError(f"Unsupported file format: {file_path}")


script_dir = os.path.dirname(os.path.abspath(__file__))
# Looking for CSV file generated by R or TSV specified by user
input_path_csv = os.path.join(script_dir, 'counts_raw.csv')
#input_path_tsv = os.path.join(script_dir, '../../../data/raw/counts_raw.tsv') # alternative option
#input_file = input_path_csv if os.path.exists(input_path_csv) else input_path_tsv
input_file = input_path_csv

output_path = os.path.join(script_dir, 'normalized_counts.tsv')

try:
    if os.path.exists(input_file):
        counts_raw = load_data(input_file)
        # Ensure that the data is numeric
        counts_raw = counts_raw.apply(pd.to_numeric, errors='coerce').dropna()

        # Running the function
        normalized_counts = normalize_deseq2_no_report(counts_raw, fast=False)
        print("Normalization completed.")

        # Saving normalized data
        print(f"Saving normalized data to {output_path}...")
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        normalized_counts.to_csv(output_path, sep='\t')
        print("Saved.")
    else:
        print(f"ERROR: Input file not found. Checked:\n- {input_path_csv}")
        sys.exit(1)

except Exception as e:
    print(f"An error occurred: {e}")
    sys.exit(1)
