import pandas as pd
import numpy as np
import os
import sys


def load_data(file_path):
  print(f"Loading data from {file_path}...")
  if not os.path.exists(file_path):
      raise FileNotFoundError(f"File not found: {file_path}")

  # Attempt to load as CSV (with commas) or TSV (with tabs)
  if file_path.endswith('.csv'):
      return pd.read_csv(file_path, index_col=0)
  elif file_path.endswith('.tsv') or file_path.endswith('.txt'):
      return pd.read_csv(file_path, sep='\t', index_col=0)
  else:
      raise ValueError(f"Unsupported file format: {file_path}")

script_dir = os.path.dirname(os.path.abspath(__file__))
# Looking for CSV file generated by R or TSV specified by user
input_path_csv = os.path.join(script_dir, '../raw/counts_raw.csv')
input_path_tsv = os.path.join(script_dir, '../../../data/raw/counts_raw.tsv') # alternative option
input_file = input_path_csv

output_path = os.path.join(script_dir, '../../../data/output/normalized_counts.tsv')

if __name__ == '__main__':
  try:
    if os.path.exists(input_file):
      counts_raw = load_data(input_file)
    else:
      print(f"ERROR: Input file not found. Checked:\n- {input_path_csv}\n- {input_path_tsv}")
      sys.exit(1)

  except Exception as e:
    print(f"An error occurred: {e}")
    sys.exit(1)