import pandas as pd
import numpy as np
import os
import sys


def normalize_raw_data(counts_raw, min_value=2, mid_value=65, max_value=255):
  """
  Two-step log min-max scaling normalization with divide point at 95 percentile. 
  """
  print("Normalizing data...")

  normalized = pd.DataFrame(1.0, index=counts_raw.index, columns=counts_raw.columns)

  log_data = np.log1p(counts_raw)
  
  flat_logs = log_data.values.flatten()
  non_zero_vals = flat_logs[flat_logs > 0]

  min_log = np.min(non_zero_vals)
  max_log = np.max(non_zero_vals)
  p95 = np.percentile(non_zero_vals, 95)

  mask_low = (log_data > 0) & (log_data <= p95)
  mask_high = (log_data > p95)

  range_low = p95 - min_log
  normalized[mask_low] = (
      (log_data[mask_low] - min_log) / range_low * (mid_value - min_value) + min_value
  )

  range_high = max_log - p95
  normalized[mask_high] = (
      (log_data[mask_high] - p95) / range_high * (max_value - (mid_value + 1)) + (mid_value + 1)
  )

  return normalized.round().astype(int)

def load_data(file_path):
  print(f"Loading data from {file_path}...")
  if not os.path.exists(file_path):
      raise FileNotFoundError(f"File not found: {file_path}")

  # Attempt to load as CSV (with commas) or TSV (with tabs)
  if file_path.endswith('.csv'):
      return pd.read_csv(file_path, index_col=0)
  elif file_path.endswith('.tsv') or file_path.endswith('.txt'):
      return pd.read_csv(file_path, sep='\t', index_col=0)
  else:
      raise ValueError(f"Unsupported file format: {file_path}")

script_dir = os.path.dirname(os.path.abspath(__file__))
# Looking for CSV file generated by R or TSV specified by user
input_path_csv = os.path.join(script_dir, '../../../data/raw/counts_raw.csv')
input_path_tsv = os.path.join(script_dir, '../../../data/raw/counts_raw.tsv') # alternative option
input_file = input_path_csv

output_path = os.path.join(script_dir, '../../../data/output/normalized_counts.tsv')

if __name__ == '__main__':
  try:
    if os.path.exists(input_file):
      counts_raw = load_data(input_file)

      normalized_counts = normalize_raw_data(counts_raw)
      os.makedirs(os.path.dirname(output_path), exist_ok=True)
      normalized_counts.to_csv(output_path, sep='\t')

    else:
      print(f"ERROR: Input file not found. Checked:\n- {input_path_csv}\n- {input_path_tsv}")
      sys.exit(1)

  except Exception as e:
    print(f"An error occurred: {e}")
    sys.exit(1)